create table if not exists public.state_profiles (
    id bigint generated by default as identity primary key,
    state_key text not null unique,
    state_name text not null,
    statute_authority text not null,
    liability_doctrine text not null,
    sync_marker text not null default to_char(now(), 'YYYY:MM'),
    is_active boolean not null default true,
    updated_at timestamptz not null default now()
);

create index if not exists state_profiles_state_key_idx on public.state_profiles (state_key);
create index if not exists state_profiles_active_idx on public.state_profiles (is_active);

create or replace function public.touch_state_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_touch_state_profiles_updated_at on public.state_profiles;
create trigger trg_touch_state_profiles_updated_at
before update on public.state_profiles
for each row
execute function public.touch_state_profiles_updated_at();

alter table public.state_profiles enable row level security;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'state_profiles'
          and policyname = 'state_profiles_read_public'
    ) then
        create policy state_profiles_read_public
            on public.state_profiles
            for select
            using (is_active = true);
    end if;
end
$$;

insert into public.state_profiles (state_key, state_name, statute_authority, liability_doctrine, sync_marker, is_active)
values
    ('alabama', 'Alabama', 'Ala. Code § 6-5-410', 'Contributory Negligence', '2026:03', true),
    ('alaska', 'Alaska', 'Alaska Stat. § 09.17.060', 'Pure Comparative Negligence', '2026:03', true),
    ('arizona', 'Arizona', 'Ariz. Rev. Stat. § 12-2505', 'Pure Comparative Negligence', '2026:03', true),
    ('arkansas', 'Arkansas', 'Ark. Code § 16-64-122', 'Modified Comparative Fault', '2026:03', true),
    ('california', 'California', 'CA Civ. Code § 1714', 'Pure Comparative Negligence', '2026:03', true),
    ('colorado', 'Colorado', 'Colo. Rev. Stat. § 13-21-111', 'Modified Comparative Fault', '2026:03', true),
    ('connecticut', 'Connecticut', 'Conn. Gen. Stat. § 52-572h', 'Modified Comparative Fault', '2026:03', true),
    ('delaware', 'Delaware', 'Del. Code tit. 10, § 8132', 'Modified Comparative Fault', '2026:03', true),
    ('florida', 'Florida', 'Fla. Stat. § 768.81', 'Modified Comparative Fault', '2026:03', true),
    ('georgia', 'Georgia', 'O.C.G.A. § 51-12-33', 'Modified Comparative Fault', '2026:03', true),
    ('hawaii', 'Hawaii', 'Haw. Rev. Stat. § 663-31', 'Modified Comparative Fault', '2026:03', true),
    ('idaho', 'Idaho', 'Idaho Code § 6-801', 'Modified Comparative Fault', '2026:03', true),
    ('illinois', 'Illinois', '735 ILCS 5/2-1116', 'Modified Comparative Fault', '2026:03', true),
    ('indiana', 'Indiana', 'Ind. Code § 34-51-2', 'Modified Comparative Fault', '2026:03', true),
    ('iowa', 'Iowa', 'Iowa Code § 668.3', 'Modified Comparative Fault', '2026:03', true),
    ('kansas', 'Kansas', 'Kan. Stat. § 60-258a', 'Modified Comparative Fault', '2026:03', true),
    ('kentucky', 'Kentucky', 'Ky. Rev. Stat. § 411.182', 'Pure Comparative Negligence', '2026:03', true),
    ('louisiana', 'Louisiana', 'La. Civ. Code art. 2323', 'Pure Comparative Fault', '2026:03', true),
    ('maine', 'Maine', '14 M.R.S. § 156', 'Modified Comparative Fault', '2026:03', true),
    ('maryland', 'Maryland', 'Md. Cts. & Jud. Proc. § 10-101', 'Contributory Negligence', '2026:03', true),
    ('massachusetts', 'Massachusetts', 'Mass. Gen. Laws ch. 231, § 85', 'Modified Comparative Fault', '2026:03', true),
    ('michigan', 'Michigan', 'Mich. Comp. Laws § 600.2959', 'Modified Comparative Fault', '2026:03', true),
    ('minnesota', 'Minnesota', 'Minn. Stat. § 604.01', 'Modified Comparative Fault', '2026:03', true),
    ('mississippi', 'Mississippi', 'Miss. Code § 11-7-15', 'Pure Comparative Negligence', '2026:03', true),
    ('missouri', 'Missouri', 'Mo. Rev. Stat. § 537.765', 'Pure Comparative Fault', '2026:03', true),
    ('montana', 'Montana', 'Mont. Code § 27-1-702', 'Modified Comparative Fault', '2026:03', true),
    ('nebraska', 'Nebraska', 'Neb. Rev. Stat. § 25-21,185.09', 'Modified Comparative Fault', '2026:03', true),
    ('nevada', 'Nevada', 'Nev. Rev. Stat. § 41.141', 'Modified Comparative Fault', '2026:03', true),
    ('new_hampshire', 'New Hampshire', 'N.H. Rev. Stat. § 507:7-d', 'Modified Comparative Fault', '2026:03', true),
    ('new_jersey', 'New Jersey', 'N.J. Stat. § 2A:15-5.1', 'Modified Comparative Fault', '2026:03', true),
    ('new_mexico', 'New Mexico', 'N.M. Stat. § 41-3A-1', 'Pure Comparative Negligence', '2026:03', true),
    ('new_york', 'New York', 'CPLR § 1411', 'Pure Comparative Negligence', '2026:03', true),
    ('north_carolina', 'North Carolina', 'N.C. Gen. Stat. § 1-139', 'Contributory Negligence', '2026:03', true),
    ('north_dakota', 'North Dakota', 'N.D. Cent. Code § 32-03.2-02', 'Modified Comparative Fault', '2026:03', true),
    ('ohio', 'Ohio', 'Ohio Rev. Code § 2315.33', 'Modified Comparative Fault', '2026:03', true),
    ('oklahoma', 'Oklahoma', '23 Okla. Stat. § 13', 'Modified Comparative Negligence', '2026:03', true),
    ('oregon', 'Oregon', 'Or. Rev. Stat. § 31.600', 'Modified Comparative Fault', '2026:03', true),
    ('pennsylvania', 'Pennsylvania', '42 Pa. Cons. Stat. § 7102', 'Modified Comparative Negligence', '2026:03', true),
    ('rhode_island', 'Rhode Island', 'R.I. Gen. Laws § 9-20-4', 'Pure Comparative Negligence', '2026:03', true),
    ('south_carolina', 'South Carolina', 'S.C. Code § 15-38-15', 'Modified Comparative Negligence', '2026:03', true),
    ('south_dakota', 'South Dakota', 'S.D. Codified Laws § 20-9-2', 'Slight/Gross Comparative Negligence', '2026:03', true),
    ('tennessee', 'Tennessee', 'McIntyre v. Balentine', 'Modified Comparative Fault', '2026:03', true),
    ('texas', 'Texas', 'TX Civ. Prac. § 33.001', 'Proportionate Responsibility', '2026:03', true),
    ('utah', 'Utah', 'Utah Code § 78B-5-818', 'Modified Comparative Fault', '2026:03', true),
    ('vermont', 'Vermont', '12 V.S.A. § 1036', 'Modified Comparative Fault', '2026:03', true),
    ('virginia', 'Virginia', 'Va. Code § 8.01-58', 'Contributory Negligence', '2026:03', true),
    ('washington', 'Washington', 'Wash. Rev. Code § 4.22.005', 'Pure Comparative Fault', '2026:03', true),
    ('west_virginia', 'West Virginia', 'W. Va. Code § 55-7-13a', 'Modified Comparative Fault', '2026:03', true),
    ('wisconsin', 'Wisconsin', 'Wis. Stat. § 895.045', 'Modified Comparative Negligence', '2026:03', true),
    ('wyoming', 'Wyoming', 'Wyo. Stat. § 1-1-109', 'Modified Comparative Fault', '2026:03', true)
on conflict (state_key) do update
set
    state_name = excluded.state_name,
    statute_authority = excluded.statute_authority,
    liability_doctrine = excluded.liability_doctrine,
    sync_marker = excluded.sync_marker,
    is_active = excluded.is_active;
